### PR TITLE
Add simple city selection based on file name

### PR DESCRIPTION
**Pull request by tobymackenzie**
You mentioned in [your post](http://meyerweb.com/eric/thoughts/2015/11/23/local-ipsum/) that you were wanting a city selection capability.  Not sure what you were going for, but this is a fairly simple solution using files in a folder representing each city / locality.  The names populate a select drop-down and and the content is in the format of the `local.txt` (now `Cleveland.txt`).  Locally I have an `Akron.txt`, so it has been tested to work with two cities.

This could at least work as a temporary solution if you had more advanced plans for the future.

### CODE REVIEW

**Comment by meyerweb** [comment]
Correct me if I’m wrong, but this doesn’t look like it will preserve a newly-selected city across multiple runs of text.  That is, if I click “Let’s do this!”, then the city selection will go back to the default city instead of the new one I picked, yes?  Or no?

**Comment by tobymackenzie** [comment]
If you select Akron and submit the form, Akron will be selected in the
select dropdown when you get the results, if that's what you mean. It won't
preserve across visits, like with a cookie, though that wouldn't be hard to
implement. I can put up a demo of the committed behavior late this evening
when i get to my personal computer.

**Comment by meyerweb** [comment]
Thanks, Toby!

**Comment by tobymackenzie** [comment]
Okay, I have [a demo up](http://www.tobymackenzie.com/local-ipsum/) with Akron in place.

**Comment by tobymackenzie** [comment]
Glad I could help.  If you want that `Akron.txt`, I could submit that too, but it could use some work.

**Pull request merged**
